openapi: 3.0.0
info:
  title: Huawei Cloud Container Engine API
  version: 1.0.0
  description: Full API specification for ProjectMan to manage projects, work items, and related entities on Huawei Cloud.
servers:
  - url: https://cce.ap-southeast-3.myhuaweicloud.com
security:
  - AuthToken: []
paths:
  /api/v3/projects/04e8e5b448000fbf2fb6c0081fcf2b5c/clusters:
    get:
      summary: List all clusters in a project
      operationId: listClusters
      parameters:
        - name: offset
          in: query
          required: true
          schema:
            type: integer
            description: "Offset"
            default: 0
        - name: limit
          in: query
          required: true
          schema:
            type: integer
            description: "Limit"
            default: 10
      responses:
        "200":
          description: A list of clusters.
          content:
            application/json:
              schema:
                type: object
                properties:
                  kind:
                    type: string
                  apiVersion:
                    type: string
                  items:
                    type: array
                    items:
                      $ref: "#/components/schemas/Cluster"
        "400":
          description: Bad request.
        "401":
          description: Unauthorized.
components:
  securitySchemes:
    AuthToken:
      type: apiKey
      name: x-auth-token
      in: header
  schemas:
    Cluster:
      type: object
      properties:
        kind:
          type: string
        apiVersion:
          type: string
        metadata:
          type: object
          properties:
            name:
              type: string
            uid:
              type: string
            creationTimestamp:
              type: string
              format: date-time
            updateTimestamp:
              type: string
              format: date-time
            labels:
              type: object
              additionalProperties:
                type: string
            annotations:
              type: object
              additionalProperties:
                type: string
            alias:
              type: string
            timezone:
              type: string
        spec:
          type: object
          properties:
            publicAccess:
              type: object
              properties:
                cidrs:
                  type: array
                  items:
                    type: string
            category:
              type: string
            type:
              type: string
            enableAutopilot:
              type: boolean
            flavor:
              type: string
            version:
              type: string
            platformVersion:
              type: string
            legacyVersion:
              type: string
            hostNetwork:
              type: object
              properties:
                vpc:
                  type: string
                subnet:
                  type: string
                SecurityGroup:
                  type: string
                controlPlaneSecurityGroup:
                  type: string
            containerNetwork:
              type: object
              properties:
                mode:
                  type: string
                cidr:
                  type: string
            eniNetwork:
              type: object
            serviceNetwork:
              type: object
              properties:
                IPv4CIDR:
                  type: string
            clusterOps:
              type: object
            authentication:
              type: object
              properties:
                mode:
                  type: string
                authenticatingProxy:
                  type: object
            billingMode:
              type: integer
            masters:
              type: array
              items:
                type: object
                properties:
                  availabilityZone:
                    type: string
            kubernetesSvcIpRange:
              type: string
            kubeProxyMode:
              type: string
            az:
              type: string
            extendParam:
              type: object
              properties:
                alpha.cce/fixPoolMask:
                  type: string
                enterpriseProjectId:
                  type: string
                kubernetes.io/cpuManagerPolicy:
                  type: string
                upgradefrom:
                  type: string
            supportIstio:
              type: boolean
            encryptionConfig:
              type: object
              properties:
                mode:
                  type: string
            deletionProtection:
              type: boolean
        status:
          type: object
          properties:
            phase:
              type: string
            endpoints:
              type: array
              items:
                type: object
                properties:
                  url:
                    type: string
                    format: uri
                  type:
                    type: string
